const imageObjs = [
	{	img:'images/placeholder.png',
		thumb:'images/placeholder.png',
		caption:'placeholder #1' },
	{	img:'images/placeholder4.png',
		thumb:'images/placeholder4.png',
		caption:'placeholder #2' },
	{	img:'images/placeholder2.png',
		thumb:'images/placeholder2.png',
		caption:'placeholder #3' },
	{	img:'images/placeholder3.png',
		thumb:'images/placeholder3.png',
		caption:'placeholder #4' },
	{	img:'images/placeholder.png',
		thumb:'images/placeholder.png',
		caption:'placeholder #5' },
	{	img:'images/placeholder4.png',
		thumb:'images/placeholder4.png',
		caption:'placeholder #6' },
	{	img:'images/placeholder2.png',
		thumb:'images/placeholder2.png',
		caption:'placeholder #7' },
	{	img:'images/placeholder3.png',
		thumb:'images/placeholder3.png',
		caption:'placeholder #8' },
	{	img:'images/placeholder.png',
		thumb:'images/placeholder.png',
		caption:'placeholder #9' },
	{	img:'images/placeholder4.png',
		thumb:'images/placeholder4.png',
		caption:'placeholder #10' }
]

module.exports = imageObjs;